### ISSUE TITLE
好像并不能很好的打开，能写个readme讲一下大概的用法吗

### ISSUE THREAD

**Issue by l-outsider** [Harry-Chen/Comment9#1]
我把压缩包下载下来cnpm install以后，经提示，额外安装了request库。

npm run start-dev 也提示找不到env命令。

我又用npx env NODE_ENV=development DEBUG=c9:* node ./bin/www.js 命令，好像也打不开。

如果这个使用ssr渲染的，我也没找到render index.ejs的代码，有点没太懂。

能写个readme讲一下大概的用法吗

**Comment by Harry-Chen** [comment]
@shankerwangmiao 是最早的开发者，请他来讲一讲吧

**Comment by Harry-Chen** [comment]
@shankerwangmiao 要不把这个 repo 放进 net9 组织去？

**Comment by l-outsider** [comment]
可以...吧，我不知道net9组织是什么(Ｔ▽Ｔ)，我是在开源软件供应链点亮计划——暑期2020中看到了这个项目，于是想了解一下

**Comment by shankerwangmiao** [comment]
@liwenchi123000 你运行的报错是啥？你用什么环境运行的？不可能没有 env 这个命令。

**Comment by Harry-Chen** [comment]
> 可以...吧，我不知道net9组织是什么(Ｔ▽Ｔ)，我是在开源软件供应链点亮计划——暑期2020中看到了这个项目，于是想了解一下

是的，我了解，你可以通过邮件告诉我你的联系方式，我们可以详细交流

**Comment by liwenchi123000** [comment]
微信：mliwenchixy




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Shengqi Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月17日(星期天) 晚上8:23
收件人:&nbsp;"Harry-Chen/Comment9"<Comment9@noreply.github.com&gt;;
抄送:&nbsp;"李文驰"<787552171@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Harry-Chen/Comment9] 好像并不能很好的打开，能写个readme讲一下大概的用法吗 (#1)





  
可以...吧，我不知道net9组织是什么(Ｔ▽Ｔ)，我是在开源软件供应链点亮计划——暑期2020中看到了这个项目，于是想了解一下
  
是的，我了解，你可以通过邮件告诉我你的联系方式，我们可以详细交流

**Comment by l-outsider** [comment]
好吧，我在windows下运行的，我linux用的不是很多，第一眼看到这个命令没反应过来




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Miao Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月17日(星期天) 晚上8:21
收件人:&nbsp;"Harry-Chen/Comment9"<Comment9@noreply.github.com&gt;;
抄送:&nbsp;"李文驰"<787552171@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Harry-Chen/Comment9] 好像并不能很好的打开，能写个readme讲一下大概的用法吗 (#1)





 
@liwenchi123000 你运行的报错是啥？你用什么环境运行的？不可能没有 env 这个命令。
